name: Debug Build for PR

on: [pull_request,workflow_dispatch]
    
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'
    - name: permission Download dependencies
      run: chmod 777 ./gradlew
    - name: Download dependencies
      run: ./gradlew androidDependencies
    - name: Build debug
      run: ./gradlew assembleDebug
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
