name: Build Debug APK

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
          

  release:
    name: Create GitHub Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Signed APK
        uses: actions/download-artifact@v4
        with:
          name: Signed-APK
          path: artifacts/

      - name: Find Downloaded APK
        run: |
          APK_PATH=$(find artifacts -name '*.apk' -print -quit)
          if [[ -z "$APK_PATH" ]]; then
            echo "No downloaded APK found!"
            exit 1
          fi
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "Downloaded APK at: $APK_PATH"

      - name: Rename APK
        run: |
          mv "${{ env.APK_PATH }}" "aShellYou-${{ github.ref_name }}-release.apk"

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Extract Changelog from strings.xml
        run: |
          VERSION_TAG="${{ github.ref_name }}"       # Example: v6.0.1
          VERSION_TAG_XML=$(echo $VERSION_TAG | tr '.' '_' | tr -d 'v')  # Convert v6.0.1 → 6_0_1
          CHANGELOG=$(xmllint --xpath "string(//string[@name='changelog_v${VERSION_TAG_XML}']/text())" app/src/main/res/values/strings.xml || echo "No changelog found for $VERSION_TAG")

          if [[ -z "$CHANGELOG" ]]; then
            echo "#### Refer to full changelogs $VERSION_TAG"
            exit 1
          fi

          # Replace • with * and \n with two spaces followed by \n
          CHANGELOG=$(echo "$CHANGELOG" | sed 's/•/*/g' | sed 's/\\n/  \n/g')

          # Add ### Changelog before the changelog text
          CHANGELOG="### Changelog  $CHANGELOG"

          # Write CHANGELOG to a temporary file
          echo -e "$CHANGELOG" > changelog.txt

      - name: Publish Release using gh CLI
        run: |
          gh release create "${{ github.ref_name }}" \
            "aShellYou-${{ github.ref_name }}-release.apk" \
            --title "aShell You ${{ github.ref_name }}" \
            --notes-file changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
